### ISSUE TITLE
PHP 7.1 Compatibility

### ISSUE THREAD

**Issue by enkota** [aldakur/wp-polr#1]
Hi,

I've just installed the plugin but cannot get into the admin settings page. 

Version: WordPress 4.9.2
Polr: 1.0.1

**Error**
`ArgumentCountError: Too few arguments to function do_settings_fields(), 1 passed in /app/public/wp-content/plugins/wp-polr/admin/settings-page.php on line 31 and exactly 2 expected in /app/public/wp-admin/includes/template.php on line 1356`

**File**
`<?php @do_settings_fields('polr-group'); ?>`

I done a bit of digging and looks to be related to PHP 7.1. Switching to 7 fixes it.

**Comment by aldakur** [comment]
Hi,

Thank you for your feedback. I'm going to try fix it to work using PHP 7.1.

Regards

**Comment by enkota** [comment]
Hey @aldakur any chance you have any time free to take a look at this? Been trying to figure out what's causing it but looks related to 7.1 requiring two arguments when calling the @do_settings_field:

`Fatal error: Uncaught ArgumentCountError: Too few arguments to function do_settings_fields(), 1 passed in /app/public/wp-content/plugins/wp-polr/admin/settings-page.php on line 31 and exactly 2 expected in`

Thanks!
